sudo: enabled
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  postgresql: "13.6"
before_install:
  - export TZ=Brazil/East
  - chmod +x mvnw
services:
  - postgresql
deploy:
  provider: heroku
  api_key:
    secure: $SECURE_KEY
  app: $APP